/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import dados.Dado;
import decorator.DecoratorBonusPenalidade;
import decorator.DecoratorDesvantagem;
import decorator.DecoratorLog;
import factory.FactoryDado;

/**
 *
 * @author rayss
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        numeroBonusTextfield.setEnabled(false);
        
        rolarDadoButton.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            rolarDado();
    }
});    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tiposDadosCombobox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        addBonusCheckbox = new javax.swing.JCheckBox();
        numeroBonusTextfield = new javax.swing.JTextField();
        dadoDesvantagemCheckbox = new javax.swing.JCheckBox();
        ativarLogCheckbox = new javax.swing.JCheckBox();
        rolarDadoButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        logDadoTextarea = new javax.swing.JTextArea();
        resultadoDadoTextfield = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tiposDadosCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "D6", "D10", "D20" }));
        tiposDadosCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiposDadosComboboxActionPerformed(evt);
            }
        });

        jLabel1.setText("Tipo de Dado:");

        addBonusCheckbox.setText("Bônus ou Penalidade");
        addBonusCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBonusCheckboxActionPerformed(evt);
            }
        });

        dadoDesvantagemCheckbox.setText("Dado com Desvantagem");
        dadoDesvantagemCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dadoDesvantagemCheckboxActionPerformed(evt);
            }
        });

        ativarLogCheckbox.setText("Ativar Log");

        rolarDadoButton.setText("Rolar Dado");

        logDadoTextarea.setColumns(20);
        logDadoTextarea.setRows(5);
        jScrollPane2.setViewportView(logDadoTextarea);

        resultadoDadoTextfield.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dadoDesvantagemCheckbox)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ativarLogCheckbox)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(resultadoDadoTextfield, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                            .addComponent(rolarDadoButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(addBonusCheckbox))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tiposDadosCombobox, 0, 201, Short.MAX_VALUE)
                                    .addComponent(numeroBonusTextfield))))
                        .addGap(77, 77, 77))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tiposDadosCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBonusCheckbox)
                    .addComponent(numeroBonusTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dadoDesvantagemCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ativarLogCheckbox)
                .addGap(18, 18, 18)
                .addComponent(rolarDadoButton)
                .addGap(18, 18, 18)
                .addComponent(resultadoDadoTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tiposDadosComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiposDadosComboboxActionPerformed

    }//GEN-LAST:event_tiposDadosComboboxActionPerformed

    private void addBonusCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBonusCheckboxActionPerformed
        numeroBonusTextfield.setEnabled(addBonusCheckbox.isSelected());
    }//GEN-LAST:event_addBonusCheckboxActionPerformed

    private void dadoDesvantagemCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dadoDesvantagemCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dadoDesvantagemCheckboxActionPerformed

    private void rolarDado() {
    String tipo = (String) tiposDadosCombobox.getSelectedItem();
    Dado dado = FactoryDado.criar(tipo);

    String descricao = tipo;

    if (addBonusCheckbox.isSelected()) {
        try {
            int bonus = Integer.parseInt(numeroBonusTextfield.getText().trim());
            dado = new DecoratorBonusPenalidade(dado, bonus);

            if (bonus >= 0) {
                descricao += "+" + bonus;
            } else {
                descricao += bonus; 
            }

        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Digite um número válido",
                    "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
    }

    if (dadoDesvantagemCheckbox.isSelected()) {
        dado = new DecoratorDesvantagem(dado);
        descricao += " com Desvantagem";
    }

    if (ativarLogCheckbox.isSelected()) {
        dado = new DecoratorLog(dado);
    }

    int resultado = dado.rolar();

    resultadoDadoTextfield.setText(String.valueOf(resultado));

    if (ativarLogCheckbox.isSelected()) {
        logDadoTextarea.append(descricao + ": " + resultado + "\n");
    }
}

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox addBonusCheckbox;
    private javax.swing.JCheckBox ativarLogCheckbox;
    private javax.swing.JCheckBox dadoDesvantagemCheckbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea logDadoTextarea;
    private javax.swing.JTextField numeroBonusTextfield;
    private javax.swing.JTextField resultadoDadoTextfield;
    private javax.swing.JButton rolarDadoButton;
    private javax.swing.JComboBox<String> tiposDadosCombobox;
    // End of variables declaration//GEN-END:variables
}
